
name: Esegui allinone.py ogni ora

on:
  schedule:
    - cron: '30 */4 * * *'  # Esegue ogni ora
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: pip install requests

      - name: Esegui lo script
        run: python allinone.py

      - name: Verifica se combined_playlist.m3u8 è stato generato
        run: |
          if [ -f "combined_playlist.m3u8" ]; then
            echo "Il file combined_playlist.m3u8 è stato generato."
          else
            echo "Il file combined_playlist.m3u8 non esiste. Esco."
            exit 0  # Esci senza fare commit o push
          fi

      - name: Aggiungi il file generato al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
        continue-on-error: true  # In caso non ci siano cambiamenti, non fallire

      - name: Pusha il cambiamento
        run: git push
        if: success()  # Esegui solo se il commit è riuscito
