name: Esegui epg.py ogni 3 ore

on:
  schedule:
    - cron: '45 */3 * * *'  # Esegue ogni 3 ore al minuto 45
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: pip install requests  # xml.etree.ElementTree è parte della libreria standard

      - name: Esegui lo script
        run: python epg.py

      - name: Verifica se epg.xml e epg.gz sono stati generati
        run: |
          if [ -f "epg.xml" ] && [ -f "epg.gzip" ]; then
            echo "File epg.xml e epg.gzip generati correttamente."
          else
            echo "Uno o entrambi i file non esistono. Esco."
            exit 0  # Esci senza fare commit o push
          fi

      - name: Aggiungi i file generati al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add epg.xml epg.gzip
          git commit -m "Aggiornamento epg.xml e epg.gzip"
        continue-on-error: true  # Evita errori se non ci sono modifiche

      - name: Pusha il cambiamento
        run: git push
        if: success()  # Esegui solo se il commit è riuscito