
name: Esegui eventsextract.py ogni 3 ore

on:
  schedule:
    - cron: '45 */3 * * *'  # Esegue ogni ora
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4

      - name: Install Playwright dependencies
        run: |
          python -m playwright install

      - name: Esegui lo script
        run: python eventsextract.py

      - name: Verifica se daddyliveSchedule.json è stato generato
        run: |
          if [ -f "daddyliveSchedule.json" ]; then
            echo "Il file daddyliveSchedule.json è stato generato."
          else
            echo "Il file daddyliveSchedule.json non esiste. Esco."
            exit 0  # Esci senza fare commit o push
          fi

      - name: Aggiungi il file generato al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daddyliveSchedule.json
        continue-on-error: true  # In caso non ci siano cambiamenti, non fallire

      - name: Pusha il cambiamento
        run: git push
        if: success()  # Esegui solo se il commit è riuscito
