name: Scarica lista eventi M3U8

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scarica-e-filtra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v2

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa le dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Esegui lo script
        run: python eventi.py

      - name: Commit e push delle modifiche
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add eventi.m3u8
          git commit -m 'Aggiornamento lista eventi M3U8' || echo 'Nessuna modifica da commitare'
          git push https://x-access-token:${GH_TOKEN}@github.com/realbestia/itatv.git

