name: Extract Schedule Data

on:
  schedule:
    - cron: '45 */3 * * *'  # Esegui ogni 3 ore
  workflow_dispatch:  # Consente l'esecuzione manuale

jobs:
  extract-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          pip install bs4
          playwright install chromium
      
      - name: Run extraction script
        run: python enevtsextract.py
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule data [skip ci]" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git)
  
