name: Scarica lista eventi M3U8

on:
  schedule:
    - cron: '0 */4 * * *'  # Esegue ogni 4 ore
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  scarica-e-filtra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa le dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Esegui lo script
        run: python script.py

      - name: Verifica se eventi.m3u8 è stato generato
        run: |
          if [ -f "eventi.m3u8" ]; then
            echo "Il file eventi.m3u8 è stato generato."
          else
            echo "Il file eventi.m3u8 non esiste. Esco."
            exit 0
          fi

      - name: Aggiungi il file generato al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Aggiornamento lista eventi M3U8"
        continue-on-error: true

      - name: Pusha il cambiamento
        run: git push
        if: success()
