name: RUN SCRIPT LISTA
on:
  schedule:
    - cron: '0 */2 * * *'  # Esegui ogni 2 ore
  workflow_dispatch:  # Consente l'esecuzione manuale

jobs:
  extract-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Chrome and ChromeDriver
        run: |
          # Installa Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Installa ChromeDriver (compatibile con la versione di Chrome)
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Verifica le installazioni
          google-chrome --version
          chromedriver --version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml playwright bs4 rapidfuzz fuzzywuzzy python-Levenshtein python-dateutil python-dotenv selenium webdriver-manager  
          playwright install 
      
      - name: Run Script
        run: |
          export $(grep -v '^#' .env | xargs)
          python "${LISTA}.py"
        env:
          # Aggiungi variabili d'ambiente per il debugging
          PYTHONUNBUFFERED: 1
      
      - name: Configura Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Stash delle modifiche locali (se presenti)
        run: |
          git diff --quiet || git stash

      - name: Scarica le ultime modifiche dal repository remoto
        run: git pull --rebase origin main

      - name: Ripristina le modifiche stashed (se presenti)
        run: |
          git stash list | grep -q "stash@{0}" && git stash pop || echo "Nessuna modifica da ripristinare"

      - name: Aggiungi il file generato al commit
        run: |
          git add .
          git commit -m "UPDATE" || echo "Nessuna modifica da commitare"

      - name: Pusha il cambiamento
        run: git push