name: Update Events

on:
  schedule:
    - cron: "0 */3 * * *" # ogni 3 ore
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (no history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests pytz
          pip install bs4
          pip install chardet
          
      - name: Run EPG grabber script
        env:
          M3U4U_EPG: ${{ secrets.M3U4U_EPG }}
        run: |
          rm -f daddyliveSchedule.json
          python itaevents.py
          
      - name: Aggiungi il file generato al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Aggiornamento lista eventi"
        continue-on-error: true

      - name: Pusha il cambiamento
        run: git push
        if: success()
