name: Esegui def.py ogni ora

on:
  schedule:
    - cron: '0 * * * *'  # Esegue ogni ora
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: pip install requests

      - name: installa fuzzywuzzy
        run: pip install fuzzywuzzy

      - name: installa python-Levenshtein
        run: pip install python-Levenshtein

      - name: Esegui lo script
        run: python def.py

      - name: Controlla se il file è stato generato
        run: |
          if [ -f "channels_italy.m3u8" ]; then
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"
              git add channels_italy.m3u8
              git commit -m "Aggiungi file generato channels_italy"
              git push
          else
              echo "Il file channels_italy.m3u8 non è stato creato, nessuna modifica da committare."
          fi