name: Esegui Def.py ogni ora
on:
  schedule:
    - cron: '0 * * * *'  # Esegue ogni ora allo scoccare dell'ora
  workflow_dispatch:  # Permette di avviare manualmente il workflow

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Puoi specificare una versione esatta, es. '3.10'

      - name: Installa le dipendenze
        run: pip install requests

      - name: Esegui lo script
        run: python def.py  # Usa il file corretto

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Aggiungi il file generato al commit
        run: |
          git add .
          git commit -m "Aggiornamento automatico di channels_italy" || true  # Evita errori se non ci sono modifiche

      - name: Recupera aggiornamenti remoti
        run: |
          git fetch origin  # Recupera gli aggiornamenti senza modificarli
          git pull origin main  # Integra i cambiamenti remoti con il tuo branch

      - name: Effettua il push
        run: git push origin main  # Esegui il push delle modifiche locali
