name: Esegui Gen.py ogni ora

on:
  schedule:
    - cron: '0 * * * *'  # Esegue ogni ora esatta
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Esegui lo script
        run: python Gen.py  # Assicurati che il file sia corretto

      - name: Verifica modifiche
        run: |
          git status
          git diff --quiet || echo "Ci sono modifiche"

      - name: Aggiungi il file generato al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit --allow-empty -m "Aggiungi file generato channels_italy" || echo "Nessuna modifica da committare"

      - name: Pusha il cambiamento
       